Repository CoHouseTeam/cohouse-server, pull requests merged in 2025-08, with the labels that each got.

#27 feat: 알림 관련 기본 뼈대 구성
  src/main/java/com/zero/cohousesever/notification/controller/NotificationController.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationReadRequestDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationRequestDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationResponseDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationSettingDto.java
  src/main/java/com/zero/cohousesever/notification/entity/Notification.java
  src/main/java/com/zero/cohousesever/notification/entity/NotificationSetting.java
  src/main/java/com/zero/cohousesever/notification/entity/NotificationType.java
  src/main/java/com/zero/cohousesever/notification/repository/NotificationRepository.java
  src/main/java/com/zero/cohousesever/notification/service/NotificationService.java
Labels: feature

#7 정산(Settlement) 서비스 및 컨트롤러 기본 뼈대 구현
  src/main/java/com/zero/cohousesever/settlement/controller/SettlementController.java
  src/main/java/com/zero/cohousesever/settlement/controller/SettlementHistoryController.java
  src/main/java/com/zero/cohousesever/settlement/dto/CreateSettlementRequest.java
  src/main/java/com/zero/cohousesever/settlement/dto/ParticipantDto.java
  src/main/java/com/zero/cohousesever/settlement/dto/PaymentCompleteRequest.java
  src/main/java/com/zero/cohousesever/settlement/dto/PaymentHistoryResponse.java
  src/main/java/com/zero/cohousesever/settlement/dto/SettlementDto.java
  src/main/java/com/zero/cohousesever/settlement/dto/SettlementHistoryResponse.java
  src/main/java/com/zero/cohousesever/settlement/entity/Participant.java
  src/main/java/com/zero/cohousesever/settlement/entity/PaymentHistory.java
  src/main/java/com/zero/cohousesever/settlement/entity/PaymentStatus.java
  src/main/java/com/zero/cohousesever/settlement/entity/Settlement.java
  src/main/java/com/zero/cohousesever/settlement/entity/SettlementCategory.java
  src/main/java/com/zero/cohousesever/settlement/entity/SettlementHistory.java
  src/main/java/com/zero/cohousesever/settlement/entity/SettlementStatus.java
  src/main/java/com/zero/cohousesever/settlement/repository/ParticipantRepository.java
  src/main/java/com/zero/cohousesever/settlement/repository/PaymentHistoryRepository.java
  src/main/java/com/zero/cohousesever/settlement/repository/SettlementRepository.java
  src/main/java/com/zero/cohousesever/settlement/service/PaymentService.java
  src/main/java/com/zero/cohousesever/settlement/service/SettlementService.java
Labels: feature

#62 Feature: #52 정산 참여자 송금 완료 및 취소 기능 추가
  src/main/java/com/zero/cohousesever/common/entity/BaseEntity.java
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/group/repository/GroupMemberRepository.java
  src/main/java/com/zero/cohousesever/member/entity/Member.java
  src/main/java/com/zero/cohousesever/post/service/PostService.java
  src/main/java/com/zero/cohousesever/settlement/controller/SettlementController.java
  src/main/java/com/zero/cohousesever/settlement/dto/CreateSettlementRequest.java
  src/main/java/com/zero/cohousesever/settlement/dto/ParticipantDto.java
  src/main/java/com/zero/cohousesever/settlement/dto/PaymentCompleteRequest.java
  src/main/java/com/zero/cohousesever/settlement/dto/SettlementDto.java
  src/main/java/com/zero/cohousesever/settlement/dto/SettlementResponseDto.java
  src/main/java/com/zero/cohousesever/settlement/entity/PaymentHistory.java
  src/main/java/com/zero/cohousesever/settlement/entity/PaymentStatus.java
  src/main/java/com/zero/cohousesever/settlement/entity/Settlement.java
  src/main/java/com/zero/cohousesever/settlement/entity/SettlementHistory.java
  src/main/java/com/zero/cohousesever/settlement/entity/SettlementParticipant.java
  src/main/java/com/zero/cohousesever/settlement/repository/ParticipantRepository.java
  src/main/java/com/zero/cohousesever/settlement/repository/PaymentHistoryRepository.java
  src/main/java/com/zero/cohousesever/settlement/repository/SettlementHistoryRepository.java
  src/main/java/com/zero/cohousesever/settlement/repository/SettlementParticipantRepository.java
  src/main/java/com/zero/cohousesever/settlement/service/PaymentService.java
  src/main/java/com/zero/cohousesever/settlement/service/SettlementService.java
  src/test/java/com/zero/cohousesever/settlement/service/SettlementServiceTest.java
Labels: feature

#88 Feature: #59 - 그룹 정보 수정 기능 구현
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/group/controller/GroupController.java
  src/main/java/com/zero/cohousesever/group/entity/Group.java
  src/main/java/com/zero/cohousesever/group/repository/GroupMemberRepository.java
  src/main/java/com/zero/cohousesever/group/service/GroupService.java
  src/test/java/com/zero/cohousesever/group/service/GroupServiceTest.java
Labels: feature

#96 Feature: #95 - 게시글 & 좋아요 기능 개선 및 안정화
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/post/controller/PostController.java
  src/main/java/com/zero/cohousesever/post/controller/PostLikeController.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikeCountResponse.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikeListResponse.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikeRequest.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikeSimpleResponse.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikeStatusResponse.java
  src/main/java/com/zero/cohousesever/post/dto/PostLikerDto.java
  src/main/java/com/zero/cohousesever/post/dto/PostUpdateRequest.java
  src/main/java/com/zero/cohousesever/post/dto/post/PostListResponse.java
  src/main/java/com/zero/cohousesever/post/dto/post/PostRequest.java
  src/main/java/com/zero/cohousesever/post/dto/post/PostResponse.java
  src/main/java/com/zero/cohousesever/post/dto/post/PostSummaryResponse.java
  src/main/java/com/zero/cohousesever/post/dto/post/PostUpdateRequest.java
  src/main/java/com/zero/cohousesever/post/dto/postLike/PostLikeCountResponse.java
  src/main/java/com/zero/cohousesever/post/dto/postLike/PostLikeListResponse.java
  src/main/java/com/zero/cohousesever/post/dto/postLike/PostLikeStatusResponse.java
  src/main/java/com/zero/cohousesever/post/dto/postLike/PostLikeToggleResponse.java
  src/main/java/com/zero/cohousesever/post/dto/postLike/PostLikerDto.java
  src/main/java/com/zero/cohousesever/post/entity/Post.java
  src/main/java/com/zero/cohousesever/post/entity/PostLike.java
  src/main/java/com/zero/cohousesever/post/repository/PostLikeRepository.java
  src/main/java/com/zero/cohousesever/post/repository/PostRepository.java
  src/main/java/com/zero/cohousesever/post/service/PostLikeService.java
  src/main/java/com/zero/cohousesever/post/service/PostService.java
  src/main/java/com/zero/cohousesever/post/type/PostColor.java
  src/test/java/com/zero/cohousesever/post/service/PostLikeServiceTest.java
  src/test/java/com/zero/cohousesever/post/service/PostServiceTest.java
Labels: feature

#104 Feature: #53 - 로그아웃 서비스 구현
  src/main/java/com/zero/cohousesever/member/controller/AuthController.java
  src/main/java/com/zero/cohousesever/member/service/AuthService.java
Labels: feature

#115 Feature: #66 - 내 그룹 정보 조회
  src/main/java/com/zero/cohousesever/group/controller/GroupController.java
  src/main/java/com/zero/cohousesever/group/repository/GroupMemberRepository.java
  src/main/java/com/zero/cohousesever/group/service/GroupService.java
  src/test/java/com/zero/cohousesever/group/service/GroupServiceTest.java
Labels: feature

#117 Feature: #97 - 그룹 초대코드 생성 기능
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/group/controller/GroupController.java
  src/main/java/com/zero/cohousesever/group/dto/group/GroupInviteDto.java
  src/main/java/com/zero/cohousesever/group/service/GroupService.java
  src/main/java/com/zero/cohousesever/group/service/InviteCodeService.java
  src/test/java/com/zero/cohousesever/group/service/GroupServiceTest.java
  src/test/java/com/zero/cohousesever/group/service/InviteCodeServiceTest.java
Labels: feature

#121 Feature: #118 - 멤버 프로필 조회
  src/main/java/com/zero/cohousesever/member/controller/ProfileController.java
  src/main/java/com/zero/cohousesever/member/dto/profile/MemberProfileSummary.java
  src/main/java/com/zero/cohousesever/member/repository/MemberRepository.java
  src/main/java/com/zero/cohousesever/member/service/MemberService.java
  src/test/java/com/zero/cohousesever/member/service/MemberServiceTest.java
Labels: feature

#123 Feature: #106 - 알림 읽음 처리 API
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/notification/controller/NotificationController.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationReadRequestDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationRequestDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationResponse.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationResponseDto.java
  src/main/java/com/zero/cohousesever/notification/dto/NotificationSettingDto.java
  src/main/java/com/zero/cohousesever/notification/dto/UnreadCountResponse.java
  src/main/java/com/zero/cohousesever/notification/entity/Notification.java
  src/main/java/com/zero/cohousesever/notification/entity/NotificationSetting.java
  src/main/java/com/zero/cohousesever/notification/entity/NotificationType.java
  src/main/java/com/zero/cohousesever/notification/repository/NotificationRepository.java
  src/main/java/com/zero/cohousesever/notification/service/NotificationService.java
  src/main/java/com/zero/cohousesever/notification/type/NotificationStatus.java
  src/main/java/com/zero/cohousesever/notification/type/NotificationType.java
  src/test/java/com/zero/cohousesever/notification/service/NotificationServiceTest.java
Labels: feature

#161 Feature: #143 프로젝트 배포를 위한 ec2 설정 및 SwaggerUI 추가
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/zero/cohousesever/notification/entity/Notification.java
  src/main/java/com/zero/cohousesever/post/entity/PostLike.java
  src/main/java/com/zero/cohousesever/post/repository/PostLikeRepository.java
  src/main/java/com/zero/cohousesever/post/service/PostLikeService.java
  src/main/java/com/zero/cohousesever/settlement/entity/Settlement.java
  src/main/java/com/zero/cohousesever/tasks/entity/enums/AssignmentStatus.java
  src/main/java/com/zero/cohousesever/tasks/entity/enums/OverrideStatus.java
  src/main/resources/application-prod.yml
  src/test/java/com/zero/cohousesever/CohouseSeverApplicationTests.java
  src/test/java/com/zero/cohousesever/member/security/JwtAuthenticationFilterTest.java
  src/test/java/com/zero/cohousesever/notification/service/NotificationServiceTest.java
  src/test/java/com/zero/cohousesever/tasks/service/RepeatDayServiceTest.java
  src/test/java/com/zero/cohousesever/tasks/service/TaskAssignmentServiceTest.java
  src/test/java/com/zero/cohousesever/tasks/service/TaskTemplateServiceTest.java
Labels: bug, feature

#170 Feature: #169 cors 정책을 위한 도메인 추가
  src/main/java/com/zero/cohousesever/common/config/WebConfig.java
Labels: feature

#167 Fix: #165 - JwtAuthenticationFilterTest 수정
  src/test/java/com/zero/cohousesever/member/security/JwtAuthenticationFilterTest.java
Labels: bug

#189 fix:188-pix-post-mapping
  src/main/java/com/zero/cohousesever/post/controller/PostController.java
  src/main/java/com/zero/cohousesever/post/service/PostService.java
Labels: bug

#198 Refactor: #197 - 게시글 & 좋아요 보완
  src/main/java/com/zero/cohousesever/common/exception/ErrorCode.java
  src/main/java/com/zero/cohousesever/group/repository/GroupMemberRepository.java
  src/main/java/com/zero/cohousesever/post/controller/PostController.java
  src/main/java/com/zero/cohousesever/post/entity/PostLike.java
  src/main/java/com/zero/cohousesever/post/repository/PostLikeRepository.java
  src/main/java/com/zero/cohousesever/post/service/PostLikeService.java
  src/main/java/com/zero/cohousesever/post/service/PostService.java
Labels: refactor
